spring:
  application:
    name: eurekaServer
  cloud:
    config:
      enabled: false

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
  instance:
    prefer-ip-address: true
  server:
    enable-self-preservation: true

logging:
  file:
    name: logs/mediLaboEurekaServer.log