
server:
  port: 5003

spring:
  application:
    name: evaluationrisqueapi

  cloud:
    config:
      enabled: false
    discovery:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health
logging:
  file:
    name: logs/mediLaboEvaluationRisqueApi.log