server:
  port: 5002
spring:
  application:
    name: noteapi
  data:
    mongodb:
      uri: mongodb://localhost:27017/dbNote
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true
eureka: 
  client: 
    service-url: 
      defaultZone: http://localhost:8761/eureka/ 
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health
logging:
  file:
    name: logs/mediLaboNoteApi.log