server:
  port: 5004

spring:
  application:
    name: authapi
  datasource:
    url: jdbc:postgresql://authdb:5432/${POSTGRES_INITDB_DATABASE}
    username: ${POSTGRES_INITDB_ROOT_USERNAME}
    password: ${POSTGRES_INITDB_ROOT_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop

  cloud:
    config:
      enabled: true
    discovery:
      enabled: true
eureka: 
  client: 
    service-url: 
      defaultZone: http://eurekaserver:8761/eureka/ 
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: health