server:
  port: 5003

spring:
  application:
    name: evaluationrisqueapi

  cloud:
    config:
      enabled: true
    discovery:
      enabled: true
eureka: 
  client: 
    service-url: 
      defaultZone: http://eurekaserver:8761/eureka/ 
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    evaluationrisqueapi:
      access: unrestricted
    health:
      show-details: always

logging:
  file:
    name: logs/mediLaboEvaluationRisqueApi.log