server:
  port: 5005  # Port du gateway

spring:
  application:
    name: gatewayapi
  cloud:
    config:
      enabled: true
    discovery:
      enabled: true
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 20s
      routes:
        - id: patientapi
          uri: lb://patientapi
          predicates:
            - Path=/api/patients/**
        - id: noteapi
          uri: lb://noteapi
          predicates:
            - Path=/api/notes/**
        - id: evaluationrisqueapi
          uri: lb://evaluationrisqueapi
          predicates:
            - Path=/api/evaluationrisque/**
        - id: authapi
          uri: lb://authapi
          predicates:
            - Path=/auth/**

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      access: unrestricted
    health:
      show-details: always
eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/
  instance:
   prefer-ip-address: true

resilience4j.circuitbreaker: 
   configs: 
     default: 
       slidingWindowSize: 20
       permittedNumberOfCallsInHalfOpenState: 3
       failureRateThreshold: 50
       waitDurationInOpenState: 5s