server:
  port: 5005  # Port du gateway

spring:
  application:
    name: gatewayapi
  cloud:
    config:
      enabled: true
    discovery:
      enabled: true
    gateway:
      routes:
        - id: patientapi
          uri: lb://patientapi
          predicates:
            - Path=/api/patients/**
          filters:
            - PreserveHostHeader=true
        - id: noteapi
          uri: lb://noteapi
          predicates:
            - Path=/api/notes/**
        - id: evaluationrisqueapi
          uri: lb://evaluationrisqueapi
          predicates:
            - Path=/api/evaluationrisque/**

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
      health:
      show-details: always
  security:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/
  instance:
   prefer-ip-address: true