server:
  port: 5002

spring:
  application:
    name: noteapi

  data:
    mongodb:
      host: mongodb
      port: 27017
      database: medilaboMongoDB
      username: mongo_admin
      password: "!eUFG8LWZ4nb2$@VBVuiLI69gre?Zb?j"
      authentication-database: admin  

  cloud:
    config:
      enabled: true
    discovery:
      enabled: true
eureka: 
  client: 
    service-url: 
      defaultZone: http://eurekaserver:8761/eureka/ 
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health
logging:
  file:
    name: logs/mediLaboNoteApi.log