server:
  port: 5000

spring:
  application:
    name: patientapi

  datasource:
    url: jdbc:mysql://mysqldb:3306/medilabo_mysql?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: medilabo_admin
    password: "!eUFG8LWZ4nb2$@VBVuiLI69gre?Zb?j"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      mode: always
      data-locations:
        - classpath:data.sql

  cloud:
    config:
      enabled: true
    discovery:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  file:
    name: logs/mediLaboPatientApi.log

eureka: 
  client: 
    service-url: 
      defaultZone: http://eurekaserver:8761/eureka/ 
  instance:
    prefer-ip-address: true