server:
  port: 5000
spring:
  profiles:
    active:
    - "prod"
  application:
    name: patientapi
  cloud:
    config:
      enabled: true
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:5555}