spring:
  datasource:
    url: jdbc:mysql://localhost:3308/medilaboDB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: medilabo_user
    password: '!eUFG8LWZ4nb2$@VBVuiLI69gre?Zb?j'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
