server:
  port: 5004

spring:
  application:
    name: authapi

  datasource:
    url: jdbc:postgresql://localhost:5432/medilabo_postgres
    username: postgres_admin
    password: "!eUFG8LWZ4nb2$@VBVuiLI69gre?Zb?j"

  jpa:
    hibernate:
      ddl-auto: create-drop
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true
eureka: 
  client: 
    service-url: 
      defaultZone: http://localhost:8761/eureka/ 
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health
security:
  jwt:
    secret-key: "3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b"
    expiration-time: 3600000