server:
  port: 5004

spring:
  application:
    name: authapi

  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres_admin
    password: "!eUFG8LWZ4nb2$@VBVuiLI69gre?Zb?j"

  jpa:
    hibernate:
      ddl-auto: create-drop
