volumes:
  mysql-data:

networks:
  spring-boot-mysql-network:
    name: spring-boot-mysql-network

services:
  mysqldb:
    image: mysql:8
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: medilaboDB
      MYSQL_USER: medilabo_user
      MYSQL_PASSWORD: '!eUFG8LWZ4nb2$@VBVuiLI69gre?Zb?j'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    networks:
      - spring-boot-mysql-network
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      retries: 5
      interval: 3s
      timeout: 30s

  patientapi:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/medilaboDB
      SPRING_DATASOURCE_USERNAME: medilabo_user
      SPRING_DATASOURCE_PASSWORD: '!eUFG8LWZ4nb2$@VBVuiLI69gre?Zb?j'
    networks:
      - spring-boot-mysql-network
